/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -m -a dbusinterfaceadaptor -i /home/fabrizio-guerriero/Scrivania/anomaly_detection_emb_workspace/anomaly_detection_emb/server/connection/dbusserver.h -l DBusServer /home/fabrizio-guerriero/Scrivania/anomaly_detection_emb_workspace/anomaly_detection_emb/dbusinterfaces/com.example.DBusInterface.xml
 *
 * qdbusxml2cpp is Copyright (C) 2022 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "dbusinterfaceadaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class DBusInterfaceAdaptor
 */

DBusInterfaceAdaptor::DBusInterfaceAdaptor(DBusServer *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

DBusInterfaceAdaptor::~DBusInterfaceAdaptor()
{
    // destructor
}

QString DBusInterfaceAdaptor::getMessage()
{
    // handle method call com.example.DBusInterface.getMessage
    return parent()->getMessage();
}


#include "dbusinterfaceadaptor.moc"
