/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -m -a dbusinterfaceadaptor -i /home/fabrizio-guerriero/Scrivania/anomaly_detection_emb_workspace/anomaly_detection_emb/server/connection/dbusserver.h -l DBusServer /home/fabrizio-guerriero/Scrivania/anomaly_detection_emb_workspace/anomaly_detection_emb/dbusinterfaces/com.example.DBusInterface.xml
 *
 * qdbusxml2cpp is Copyright (C) 2022 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef DBUSINTERFACEADAPTOR_H
#define DBUSINTERFACEADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "/home/fabrizio-guerriero/Scrivania/anomaly_detection_emb_workspace/anomaly_detection_emb/server/connection/dbusserver.h"
#include <QtCore/qcontainerfwd.h>

/*
 * Adaptor class for interface com.example.DBusInterface
 */
class DBusInterfaceAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.example.DBusInterface")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.example.DBusInterface\">\n"
"    <method name=\"getMessage\">\n"
"      <arg direction=\"out\" type=\"s\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    DBusInterfaceAdaptor(DBusServer *parent);
    virtual ~DBusInterfaceAdaptor();

    inline DBusServer *parent() const
    { return static_cast<DBusServer *>(QObject::parent()); }

public: // PROPERTIES
public Q_SLOTS: // METHODS
    QString getMessage();
Q_SIGNALS: // SIGNALS
};

#endif
