/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -a dbusserver_interface com.example.DBusInterface.xml
 *
 * qdbusxml2cpp is Copyright (C) 2022 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "dbusserver_interface.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class DBusInterfaceAdaptor
 */

DBusInterfaceAdaptor::DBusInterfaceAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

DBusInterfaceAdaptor::~DBusInterfaceAdaptor()
{
    // destructor
}

QString DBusInterfaceAdaptor::getMessage()
{
    // handle method call com.example.DBusInterface.getMessage
    QString out0;
    QMetaObject::invokeMethod(parent(), "getMessage", Q_RETURN_ARG(QString, out0));
    return out0;
}

