/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -a dbusserver_interface com.example.DBusInterface.xml
 *
 * qdbusxml2cpp is Copyright (C) 2022 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef DBUSSERVER_INTERFACE_H
#define DBUSSERVER_INTERFACE_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
//class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface com.example.DBusInterface
 */
class DBusInterfaceAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.dbus_example.DBusService")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.dbus_example.DBusService\">\n"
"    <method name=\"getMessage\">\n"
"      <arg direction=\"out\" type=\"s\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    DBusInterfaceAdaptor(QObject *parent);
    virtual ~DBusInterfaceAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    QString getMessage();
Q_SIGNALS: // SIGNALS
};

#endif
