/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp com.bikeDashboard.ParameterManager.xml -a parameters_adaptor
 *
 * qdbusxml2cpp is Copyright (C) 2022 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef PARAMETERS_ADAPTOR_H
#define PARAMETERS_ADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include <QStringList>

QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
QT_END_NAMESPACE

/*
 * Adaptor class for interface com.bikeDashboard.Parameter
 */
class ParameterAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.bikeDashboard.Parameter")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.bikeDashboard.Parameter\">\n"
"    <method name=\"GetValue\">\n"
"      <arg direction=\"out\" type=\"v\"/>\n"
"    </method>\n"
"    <method name=\"SetValue\">\n"
"      <arg direction=\"in\" type=\"v\"/>\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"    </method>\n"
"    <method name=\"Reset\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"    </method>\n"
"    <property access=\"read\" type=\"s\" name=\"Id\"/>\n"
"    <property access=\"read\" type=\"s\" name=\"Unit\"/>\n"
"    <property access=\"read\" type=\"s\" name=\"Type\"/>\n"
"    <property access=\"read\" type=\"v\" name=\"Value\"/>\n"
"    <property access=\"read\" type=\"v\" name=\"DefaultValue\"/>\n"
"    <property access=\"read\" type=\"v\" name=\"Min\"/>\n"
"    <property access=\"read\" type=\"v\" name=\"Max\"/>\n"
"    <signal name=\"ValueChanged\">\n"
"      <arg type=\"v\"/>\n"
"    </signal>\n"
"  </interface>\n"
        "")
public:
    ParameterAdaptor(QObject *parent);
    virtual ~ParameterAdaptor();

public: // PROPERTIES
    Q_PROPERTY(QString Id READ id)
    QString id() const;

    Q_PROPERTY(QVariant DefaultValue READ defaultValue)
    QVariant defaultValue() const;

    Q_PROPERTY(QVariant Max READ max)
    QVariant max() const;

    Q_PROPERTY(QVariant Min READ min)
    QVariant min() const;

    Q_PROPERTY(QString Type READ type)
    QString type() const;

    Q_PROPERTY(QString Unit READ unit)
    QString unit() const;

    Q_PROPERTY(QVariant Value READ value)
    QVariant value() const;

public Q_SLOTS: // METHODS
    QVariant GetValue();
    bool Reset();
    bool SetValue(const QVariant &in0);
Q_SIGNALS: // SIGNALS
    void ValueChanged(const QVariant &in0);
};

/*
 * Adaptor class for interface com.bikeDashboard.ParameterManager
 */
class ParameterManagerAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.bikeDashboard.ParameterManager")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.bikeDashboard.ParameterManager\">\n"
"    <method name=\"ListParameters\">\n"
"      <arg direction=\"out\" type=\"as\"/>\n"
"    </method>\n"
"    <method name=\"GetParameter\">\n"
"      <arg direction=\"in\" type=\"s\"/>\n"
"      <arg direction=\"out\" type=\"o\"/>\n"
"    </method>\n"
"    <method name=\"GetParameterInfo\">\n"
"      <arg direction=\"in\" type=\"s\"/>\n"
"      <arg direction=\"out\" type=\"a{sv}\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    ParameterManagerAdaptor(QObject *parent);
    virtual ~ParameterManagerAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    QDBusObjectPath GetParameter(const QString &in0);
    QVariantMap GetParameterInfo(const QString &in0);
    QStringList ListParameters();
Q_SIGNALS: // SIGNALS
};

#endif
