/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp com.bikeDashboard.ParameterManager.xml -a parameters_adaptor
 *
 * qdbusxml2cpp is Copyright (C) 2022 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "parameters_adaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class ParameterAdaptor
 */

ParameterAdaptor::ParameterAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

ParameterAdaptor::~ParameterAdaptor()
{
    // destructor
}

QString ParameterAdaptor::id() const
{
    // get the value of property Id
    return qvariant_cast< QString >(parent()->property("Id"));
}

QVariant ParameterAdaptor::defaultValue() const
{
    // get the value of property DefaultValue
    return qvariant_cast< QVariant >(parent()->property("DefaultValue"));
}

QVariant ParameterAdaptor::max() const
{
    // get the value of property Max
    return qvariant_cast< QVariant >(parent()->property("Max"));
}

QVariant ParameterAdaptor::min() const
{
    // get the value of property Min
    return qvariant_cast< QVariant >(parent()->property("Min"));
}

QString ParameterAdaptor::type() const
{
    // get the value of property Type
    return qvariant_cast< QString >(parent()->property("Type"));
}

QString ParameterAdaptor::unit() const
{
    // get the value of property Unit
    return qvariant_cast< QString >(parent()->property("Unit"));
}

QVariant ParameterAdaptor::value() const
{
    // get the value of property Value
    return qvariant_cast< QVariant >(parent()->property("Value"));
}

QVariant ParameterAdaptor::GetValue()
{
    // handle method call com.bikeDashboard.Parameter.GetValue
    QVariant out0;
    QMetaObject::invokeMethod(parent(), "GetValue", Q_RETURN_ARG(QVariant, out0));
    return out0;
}

bool ParameterAdaptor::Reset()
{
    // handle method call com.bikeDashboard.Parameter.Reset
    bool out0;
    QMetaObject::invokeMethod(parent(), "Reset", Q_RETURN_ARG(bool, out0));
    return out0;
}

bool ParameterAdaptor::SetValue(const QVariant &in0)
{
    // handle method call com.bikeDashboard.Parameter.SetValue
    bool out0;
    QMetaObject::invokeMethod(parent(), "SetValue", Q_RETURN_ARG(bool, out0), Q_ARG(QVariant, in0));
    return out0;
}

/*
 * Implementation of adaptor class ParameterManagerAdaptor
 */

ParameterManagerAdaptor::ParameterManagerAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

ParameterManagerAdaptor::~ParameterManagerAdaptor()
{
    // destructor
}

QDBusObjectPath ParameterManagerAdaptor::GetParameter(const QString &in0)
{
    // handle method call com.bikeDashboard.ParameterManager.GetParameter
    QDBusObjectPath out0;
    QMetaObject::invokeMethod(parent(), "GetParameter", Q_RETURN_ARG(QDBusObjectPath, out0), Q_ARG(QString, in0));
    return out0;
}

QVariantMap ParameterManagerAdaptor::GetParameterInfo(const QString &in0)
{
    // handle method call com.bikeDashboard.ParameterManager.GetParameterInfo
    QVariantMap out0;
    QMetaObject::invokeMethod(parent(), "GetParameterInfo", Q_RETURN_ARG(QVariantMap, out0), Q_ARG(QString, in0));
    return out0;
}

QStringList ParameterManagerAdaptor::ListParameters()
{
    // handle method call com.bikeDashboard.ParameterManager.ListParameters
    QStringList out0;
    QMetaObject::invokeMethod(parent(), "ListParameters", Q_RETURN_ARG(QStringList, out0));
    return out0;
}
